# Generated by Django 4.1 on 2022-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=20)),
                ("lastName", models.CharField(max_length=20)),
                ("age", models.IntegerField(default=18)),
                ("gender", models.CharField(max_length=20)),
                ("prefferedWorkType", models.CharField(max_length=20)),
                ("cvUrl", models.CharField(max_length=2080)),
                ("aadharId", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("mobileNumber", models.IntegerField()),
                ("address", models.TextField(max_length=3000)),
                ("location", models.TextField(max_length=50)),
                ("state", models.TextField(max_length=50)),
                ("readyToRelocate", models.BooleanField(default=False)),
                ("hasDrivingLicence", models.BooleanField(default=False)),
                ("hasVehicle", models.BooleanField(default=False)),
                ("expectedWagePerHour", models.IntegerField()),
                ("expectedWorkingHoursPerWeek", models.IntegerField()),
                ("isTechnicalWorker", models.BooleanField(verbose_name=False)),
                ("isOccupied", models.BooleanField(default=False)),
                ("isBlocked", models.BooleanField(default=False)),
                ("physicalHealthPoints", models.IntegerField()),
                ("mentalHealthPoints", models.IntegerField()),
            ],
        ),
    ]
