# Generated by Django 4.1 on 2022-08-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unorganized_workers_data", "0002_alter_employees_istechnicalworker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="address",
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="employees", name="email", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="employees",
            name="location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="employees", name="state", field=models.CharField(max_length=50),
        ),
    ]
