# Generated by Django 4.1 on 2022-08-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unorganized_workers_data', '0004_alter_employees_cvurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='knowsToOperateMobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='knowsToReadAndWrite',
            field=models.BooleanField(default=False),
        ),
    ]
